"""Static catalog of DataPilot tools.

This module lists what exists. It does not execute tools, look up functions by
name from user input, or run Python/SQL generated by a model.
"""

from __future__ import annotations

from app.ai.schemas import ToolDefinition, ToolParameterSchema, ToolParametersSchema

_DATASET_ID = ToolParameterSchema(
    type="string",
    description="Registry id returned by CSV upload. Never a filesystem path.",
)
_COLUMN = ToolParameterSchema(
    type="string",
    description="Exact column name from the uploaded dataset.",
)


TOOL_DEFINITIONS: tuple[ToolDefinition, ...] = (
    ToolDefinition(
        name="get_dataset_summary",
        description=(
            "Return row/column counts, column names, and duplicate-row stats "
            "for an uploaded dataset."
        ),
        parameters=ToolParametersSchema(
            properties={"dataset_id": _DATASET_ID},
            required=["dataset_id"],
        ),
    ),
    ToolDefinition(
        name="get_column_profile",
        description=(
            "Return the profiler result for one column: inferred type, unique "
            "count, and numeric or categorical summary."
        ),
        parameters=ToolParametersSchema(
            properties={"dataset_id": _DATASET_ID, "column": _COLUMN},
            required=["dataset_id", "column"],
        ),
    ),
    ToolDefinition(
        name="get_numeric_statistics",
        description=(
            "Return mean, median, std, min, max, quartiles, IQR, and IQR "
            "outlier information for one numeric column."
        ),
        parameters=ToolParametersSchema(
            properties={"dataset_id": _DATASET_ID, "column": _COLUMN},
            required=["dataset_id", "column"],
        ),
    ),
    ToolDefinition(
        name="get_correlations",
        description=(
            "Return pairwise Pearson correlations between numeric columns."
        ),
        parameters=ToolParametersSchema(
            properties={"dataset_id": _DATASET_ID},
            required=["dataset_id"],
        ),
    ),
    ToolDefinition(
        name="get_outliers",
        description=(
            "Return IQR-fence outlier counts, fences, and a small sample of "
            "outlier values for one numeric column."
        ),
        parameters=ToolParametersSchema(
            properties={"dataset_id": _DATASET_ID, "column": _COLUMN},
            required=["dataset_id", "column"],
        ),
    ),
    ToolDefinition(
        name="get_histogram",
        description=(
            "Return aggregated histogram bin counts for a numeric column. "
            "Does not return raw rows. Bins are clamped to 5–50."
        ),
        parameters=ToolParametersSchema(
            properties={
                "dataset_id": _DATASET_ID,
                "column": _COLUMN,
                "bins": ToolParameterSchema(
                    type="integer",
                    description="Requested bin count. Clamped to 5–50.",
                    default=20,
                ),
            },
            required=["dataset_id", "column"],
        ),
    ),
    ToolDefinition(
        name="get_category_counts",
        description=(
            "Return top category counts for a categorical column. "
            "Does not return the full high-cardinality domain. Limit is 1–50."
        ),
        parameters=ToolParametersSchema(
            properties={
                "dataset_id": _DATASET_ID,
                "column": _COLUMN,
                "limit": ToolParameterSchema(
                    type="integer",
                    description="Maximum categories to return. Clamped to 1–50.",
                    default=15,
                ),
            },
            required=["dataset_id", "column"],
        ),
    ),
    ToolDefinition(
        name="get_scatter_data",
        description=(
            "Return sampled scatter points for two numeric columns. "
            "Does not return the full dataset. Point count is clamped to 10–2000."
        ),
        parameters=ToolParametersSchema(
            properties={
                "dataset_id": _DATASET_ID,
                "x_column": ToolParameterSchema(
                    type="string",
                    description="Numeric column for the x axis.",
                ),
                "y_column": ToolParameterSchema(
                    type="string",
                    description="Numeric column for the y axis.",
                ),
                "max_points": ToolParameterSchema(
                    type="integer",
                    description="Maximum points to return. Clamped to 10–2000.",
                    default=500,
                ),
            },
            required=["dataset_id", "x_column", "y_column"],
        ),
    ),
    ToolDefinition(
        name="get_correlation_heatmap",
        description=(
            "Return the Pearson correlation matrix and numeric column names. "
            "Uses the same correlation implementation as get_correlations."
        ),
        parameters=ToolParametersSchema(
            properties={"dataset_id": _DATASET_ID},
            required=["dataset_id"],
        ),
    ),
)

TOOL_NAMES: frozenset[str] = frozenset(item.name for item in TOOL_DEFINITIONS)


def list_tool_definitions() -> list[ToolDefinition]:
    """Return the static catalog. Safe to expose over HTTP."""
    return list(TOOL_DEFINITIONS)
